import Head from "next/head";
import Card from "../components/card";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-6 bg-gray-50">
        <div className="hidden sm:inline">
          <h2 className="font-bold text-3xl m-4">Categories</h2>
          <ul className="flex flex-col pl-4">
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 1
              </a>
            </li>
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 2
              </a>
            </li>
          </ul>
        </div>
        <div className="col-span-6 grid grid-cols-1 sm:grid-cols-3 sm:col-span-4">
          <h1 className="hidden sm:inline sm:col-span-3 m-4 font-bold text-3xl">
            All
          </h1>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
        <div className="hidden sm:inline">3</div>
      </div>
    </div>
  );
}
