import Head from "next/head";
import Card from "../components/card";
import Carousel from "../components/carousel";
import firebase from "../config/firebase";
import { useRouter } from "next/router";

export default function Home(props) {
  const router = useRouter();
  console.log(props);
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <div className="grid grid-cols-6 bg-ivory-dark pattern">
        <div className="hidden sm:inline">
          <h2 className="font-bold text-xl m-4">Categories</h2>
          <ul className="flex flex-col pl-4">
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 1
              </a>
            </li>
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 2
              </a>
            </li>
          </ul>
        </div>
        <div className="col-span-6 grid grid-cols-1 sm:grid-cols-4 sm:col-span-4">
          <h1 className="hidden sm:inline sm:col-span-4 m-4 font-bold text-xl">
            All
          </h1>
          {Object.keys(props).map((item) => (
            <Card
              url={props[item].imageurl}
              name={props[item].name}
              price={props[item].price}
              id={props[item].id}
            />
          ))}
        </div>
        <div className="hidden sm:inline">
          <h2 className="font-bold text-xl mt-4 ml-6">Relevance</h2>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const list = [];
  const res = await firebase.firestore().collection("all").get();
  res.docs.forEach((doc) => {
    const newData = { ...doc.data(), id: doc.id };
    list.push(newData);
  });
  const obj = { ...list };
  return { props: obj };
}
