import Head from "next/head";
import Card from "../components/card";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-6 bg-gray-50 pattern">
        <div className="hidden sm:inline">
          <h2 className="font-bold text-xl m-4">Categories</h2>
          <ul className="flex flex-col pl-4">
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 1
              </a>
            </li>
            <li>
              <a href="#" className="hover:text-blue-600">
                Category 2
              </a>
            </li>
          </ul>
        </div>
        <div className="col-span-6 grid grid-cols-1 sm:grid-cols-4 sm:col-span-4">
          <h1 className="hidden sm:inline sm:col-span-4 m-4 font-bold text-xl">
            All
          </h1>
          <Card url="/drawsta_random_tee.jpg" />
          <Card url="/index.jpeg" />
          <Card url="/index1.jpeg" />
          <Card url="/images.jpeg" />
          <Card url="/images2.jpeg" />
        </div>
        <div className="hidden sm:inline">
          <h2 className="font-bold text-xl mt-4 ml-6">Relevance</h2>
        </div>
      </div>
    </div>
  );
}
